"""Storage: users, plans and run counts.

Two backends behind one API. Set DATABASE_URL to a Postgres connection string
(Neon, or any Postgres) and it is used; leave it unset and the app falls back to
a local SQLite file, which keeps `git clone && uvicorn` working with no service
to provision.

Queries are written once with '?' placeholders and rewritten for Postgres, and
both drivers hand back rows that behave like dicts, so callers do not care which
backend is live.
"""

from __future__ import annotations

import sqlite3
from contextlib import contextmanager
from datetime import datetime, timezone
from typing import Any, Iterator, Mapping, Optional

from config import DATABASE_URL, DB_PATH

Row = Mapping[str, Any]

IS_POSTGRES = bool(DATABASE_URL)

_pool = None

if IS_POSTGRES:  # pragma: no cover - exercised only with DATABASE_URL set
    from psycopg.rows import dict_row
    from psycopg_pool import ConnectionPool

    # Neon sits behind a pooler and can drop idle connections, so keep the pool
    # small, recycle connections, and check them out healthy.
    _pool = ConnectionPool(
        DATABASE_URL,
        min_size=0,
        max_size=5,
        max_idle=120,
        kwargs={"row_factory": dict_row, "autocommit": False},
        open=False,
    )


# --- schema -----------------------------------------------------------------
_SQLITE_SCHEMA = """
CREATE TABLE IF NOT EXISTS users (
    id                  INTEGER PRIMARY KEY AUTOINCREMENT,
    email               TEXT    NOT NULL UNIQUE,
    password_hash       TEXT    NOT NULL,
    plan                TEXT    NOT NULL DEFAULT 'free',
    stripe_customer_id  TEXT,
    plan_renews_at      TEXT,
    created_at          TEXT    NOT NULL
);

CREATE TABLE IF NOT EXISTS runs (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id     INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    created_at  TEXT    NOT NULL,
    companies   TEXT    NOT NULL DEFAULT '',
    found       INTEGER NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_runs_user_time ON runs(user_id, created_at);
CREATE INDEX IF NOT EXISTS idx_users_customer ON users(stripe_customer_id);

CREATE TABLE IF NOT EXISTS opening_sightings (
    url         TEXT    PRIMARY KEY,
    company     TEXT    NOT NULL DEFAULT '',
    title       TEXT    NOT NULL DEFAULT '',
    source      TEXT    NOT NULL DEFAULT '',
    posted_at   TEXT,
    first_seen  TEXT    NOT NULL,
    last_seen   TEXT    NOT NULL,
    times_seen  INTEGER NOT NULL DEFAULT 1
);

CREATE INDEX IF NOT EXISTS idx_sightings_company ON opening_sightings(company, first_seen);

CREATE TABLE IF NOT EXISTS user_seen (
    user_id     INTEGER    NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    kind        TEXT    NOT NULL,
    url         TEXT    NOT NULL,
    first_seen  TEXT    NOT NULL,
    last_seen   TEXT    NOT NULL,
    times_seen  INTEGER NOT NULL DEFAULT 1,
    PRIMARY KEY (user_id, kind, url)
);

CREATE INDEX IF NOT EXISTS idx_user_seen_lookup ON user_seen(user_id, kind, last_seen);
"""

_POSTGRES_SCHEMA = """
CREATE TABLE IF NOT EXISTS users (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email               TEXT   NOT NULL UNIQUE,
    password_hash       TEXT   NOT NULL,
    plan                TEXT   NOT NULL DEFAULT 'free',
    stripe_customer_id  TEXT,
    plan_renews_at      TEXT,
    created_at          TEXT   NOT NULL
);

CREATE TABLE IF NOT EXISTS runs (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    created_at  TEXT   NOT NULL,
    companies   TEXT   NOT NULL DEFAULT '',
    found       INTEGER NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_runs_user_time ON runs(user_id, created_at);
CREATE INDEX IF NOT EXISTS idx_users_customer ON users(stripe_customer_id);

CREATE TABLE IF NOT EXISTS opening_sightings (
    url         TEXT    PRIMARY KEY,
    company     TEXT    NOT NULL DEFAULT '',
    title       TEXT    NOT NULL DEFAULT '',
    source      TEXT    NOT NULL DEFAULT '',
    posted_at   TEXT,
    first_seen  TEXT    NOT NULL,
    last_seen   TEXT    NOT NULL,
    times_seen  INTEGER NOT NULL DEFAULT 1
);

CREATE INDEX IF NOT EXISTS idx_sightings_company ON opening_sightings(company, first_seen);

CREATE TABLE IF NOT EXISTS user_seen (
    user_id     BIGINT     NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    kind        TEXT    NOT NULL,
    url         TEXT    NOT NULL,
    first_seen  TEXT    NOT NULL,
    last_seen   TEXT    NOT NULL,
    times_seen  INTEGER NOT NULL DEFAULT 1,
    PRIMARY KEY (user_id, kind, url)
);

CREATE INDEX IF NOT EXISTS idx_user_seen_lookup ON user_seen(user_id, kind, last_seen);
"""


def _now() -> str:
    return datetime.now(timezone.utc).isoformat()


def month_start() -> str:
    now = datetime.now(timezone.utc)
    return now.replace(day=1, hour=0, minute=0, second=0, microsecond=0).isoformat()


def _q(sql: str) -> str:
    """'?' placeholders are written once; Postgres wants '%s'."""
    return sql.replace("?", "%s") if IS_POSTGRES else sql


def _ensure_pool_open() -> None:
    """Open the pool on first use.

    The pool is constructed with open=False so importing this module never
    reaches out to the network. Opening lazily here means any entry point works
    — the app's lifespan, a one-off script, a test — not just the paths that
    happen to call init_db() first. ConnectionPool.open() is a no-op once open.
    """
    assert _pool is not None
    _pool.open()


@contextmanager
def connect() -> Iterator[Any]:
    """A connection that commits on success and always closes/returns itself."""
    if IS_POSTGRES:
        _ensure_pool_open()
        assert _pool is not None
        with _pool.connection() as conn:   # commits on clean exit, rolls back on error
            yield conn
        return

    DB_PATH.parent.mkdir(parents=True, exist_ok=True)
    conn = sqlite3.connect(DB_PATH, timeout=10.0)
    conn.row_factory = sqlite3.Row
    conn.execute("PRAGMA foreign_keys = ON")
    try:
        yield conn
        conn.commit()
    finally:
        conn.close()


def _fetchone(conn: Any, sql: str, params: tuple) -> Optional[Row]:
    if IS_POSTGRES:
        with conn.cursor() as cur:
            cur.execute(_q(sql), params)
            return cur.fetchone()
    return conn.execute(sql, params).fetchone()


def _run(conn: Any, sql: str, params: tuple) -> int:
    """Execute a write; returns the number of rows affected."""
    if IS_POSTGRES:
        with conn.cursor() as cur:
            cur.execute(_q(sql), params)
            return cur.rowcount
    return conn.execute(sql, params).rowcount


def init_db() -> None:
    if IS_POSTGRES:
        with connect() as conn, conn.cursor() as cur:
            cur.execute(_POSTGRES_SCHEMA)
        return

    with connect() as conn:
        conn.executescript(_SQLITE_SCHEMA)


# --- users -------------------------------------------------------------------
def create_user(email: str, password_hash: str) -> int:
    sql = "INSERT INTO users (email, password_hash, created_at) VALUES (?, ?, ?)"
    with connect() as conn:
        if IS_POSTGRES:
            row = _fetchone(conn, sql + " RETURNING id", (email, password_hash, _now()))
            return int(row["id"])
        cur = conn.execute(sql, (email, password_hash, _now()))
        return int(cur.lastrowid)


def get_user_by_email(email: str) -> Optional[Row]:
    with connect() as conn:
        return _fetchone(conn, "SELECT * FROM users WHERE email = ?", (email,))


def get_user(user_id: int) -> Optional[Row]:
    with connect() as conn:
        return _fetchone(conn, "SELECT * FROM users WHERE id = ?", (user_id,))


def set_stripe_customer(user_id: int, customer_id: str) -> None:
    with connect() as conn:
        _run(conn, "UPDATE users SET stripe_customer_id = ? WHERE id = ?", (customer_id, user_id))


def set_plan(user_id: int, plan: str, renews_at: str | None = None) -> None:
    with connect() as conn:
        _run(conn, "UPDATE users SET plan = ?, plan_renews_at = ? WHERE id = ?",
             (plan, renews_at, user_id))


def set_plan_by_customer(customer_id: str, plan: str, renews_at: str | None = None) -> bool:
    with connect() as conn:
        return _run(conn,
                    "UPDATE users SET plan = ?, plan_renews_at = ? WHERE stripe_customer_id = ?",
                    (plan, renews_at, customer_id)) > 0


# --- runs / quota ------------------------------------------------------------
def record_run(user_id: int, companies: str, found: int) -> None:
    with connect() as conn:
        _run(conn, "INSERT INTO runs (user_id, created_at, companies, found) VALUES (?, ?, ?, ?)",
             (user_id, _now(), companies, found))


def runs_this_month(user_id: int) -> int:
    with connect() as conn:
        row = _fetchone(conn,
                        "SELECT COUNT(*) AS n FROM runs WHERE user_id = ? AND created_at >= ?",
                        (user_id, month_start()))
        return int(row["n"]) if row else 0


def close() -> None:
    """Release pooled connections. Without this the pool's worker threads are
    still alive at interpreter shutdown and psycopg_pool raises from __del__."""
    if IS_POSTGRES and _pool is not None:
        _pool.close()


def backend_name() -> str:
    return "postgres" if IS_POSTGRES else "sqlite"


# --- opening sightings -------------------------------------------------------
# Neither Greenhouse nor Lever exposes history: their feeds return what is open
# right now, and nothing published anywhere says when a company opened the same
# role last year. So predicting a hiring window cannot be looked up -- it has to
# be accumulated. Every run records the postings it saw, and after a cycle or
# two `company_history` has genuine per-company dates that were observed rather
# than guessed.

_UPSERT_SIGHTING = """
INSERT INTO opening_sightings
    (url, company, title, source, posted_at, first_seen, last_seen, times_seen)
VALUES (?, ?, ?, ?, ?, ?, ?, 1)
ON CONFLICT (url) DO UPDATE SET
    last_seen  = excluded.last_seen,
    times_seen = opening_sightings.times_seen + 1,
    -- a date only ever gets filled in, never overwritten with a blank
    posted_at  = COALESCE(opening_sightings.posted_at, excluded.posted_at),
    company    = CASE WHEN opening_sightings.company = ''
                      THEN excluded.company ELSE opening_sightings.company END,
    title      = CASE WHEN opening_sightings.title = ''
                      THEN excluded.title ELSE opening_sightings.title END
"""


def record_sightings(openings: list) -> dict[str, str]:
    """Record this run's postings; return {url: first_seen} for all of them.

    first_seen is the first time *this app* saw the posting, which is an upper
    bound on when it opened, not the opening date. Callers must keep the two
    apart: posted_at is the board's own claim, first_seen is ours.
    """
    if not openings:
        return {}

    now = _now()
    rows = [
        (o.url, (o.company or "")[:80], (o.title or "")[:160], o.source or "",
         getattr(o, "posted_at", None), now, now)
        for o in openings
    ]
    urls = [r[0] for r in rows]
    marks = ",".join("?" for _ in urls)

    with connect() as conn:
        if IS_POSTGRES:
            with conn.cursor() as cur:
                cur.executemany(_q(_UPSERT_SIGHTING), rows)
                cur.execute(
                    _q(f"SELECT url, first_seen FROM opening_sightings WHERE url IN ({marks})"),
                    tuple(urls),
                )
                found = cur.fetchall()
        else:
            conn.executemany(_UPSERT_SIGHTING, rows)
            found = conn.execute(
                f"SELECT url, first_seen FROM opening_sightings WHERE url IN ({marks})",
                tuple(urls),
            ).fetchall()

    return {row["url"]: row["first_seen"] for row in found}


def company_history(company: str, limit: int = 200) -> list[Row]:
    """Every posting observed for one company, oldest first.

    This is the raw material for answering "when does this company open
    applications" -- deliberately raw, because until a full cycle has been
    observed the only honest answer is that there is not enough data yet.
    """
    with connect() as conn:
        sql = (
            "SELECT url, title, source, posted_at, first_seen, last_seen, times_seen "
            "FROM opening_sightings WHERE LOWER(company) = ? "
            "ORDER BY first_seen ASC LIMIT ?"
        )
        params = ((company or "").strip().lower(), limit)
        if IS_POSTGRES:
            with conn.cursor() as cur:
                cur.execute(_q(sql), params)
                return list(cur.fetchall())
        return list(conn.execute(sql, params).fetchall())


def sightings_count() -> int:
    with connect() as conn:
        row = _fetchone(conn, "SELECT COUNT(*) AS n FROM opening_sightings", ())
        return int(row["n"]) if row else 0


# --- what a user has already been shown --------------------------------------
# Repeat runs used to return the same faces: the queries are identical, so
# Google returns the same top results forever. Remembering per user what has
# already been shown lets a later run skip it and dig deeper instead.

_UPSERT_SEEN = """
INSERT INTO user_seen (user_id, kind, url, first_seen, last_seen, times_seen)
VALUES (?, ?, ?, ?, ?, 1)
ON CONFLICT (user_id, kind, url) DO UPDATE SET
    last_seen  = excluded.last_seen,
    times_seen = user_seen.times_seen + 1
"""


def record_seen(user_id: int, kind: str, urls: list[str]) -> None:
    """Remember that this user has now been shown these results."""
    if not urls:
        return
    now = _now()
    rows = [(user_id, kind, u, now, now) for u in dict.fromkeys(urls)]
    with connect() as conn:
        if IS_POSTGRES:
            with conn.cursor() as cur:
                cur.executemany(_q(_UPSERT_SEEN), rows)
        else:
            conn.executemany(_UPSERT_SEEN, rows)


def seen_urls(user_id: int, kind: str, limit: int = 5000) -> set[str]:
    """URLs this user has already been shown, most recent first.

    Capped because it is sent into every query filter; a user far past the cap
    simply starts seeing the oldest results again, which beats an unbounded
    query.
    """
    sql = ("SELECT url FROM user_seen WHERE user_id = ? AND kind = ? "
           "ORDER BY last_seen DESC LIMIT ?")
    with connect() as conn:
        if IS_POSTGRES:
            with conn.cursor() as cur:
                cur.execute(_q(sql), (user_id, kind, limit))
                return {r["url"] for r in cur.fetchall()}
        return {r["url"] for r in conn.execute(sql, (user_id, kind, limit)).fetchall()}


def forget_seen(user_id: int, kind: str | None = None) -> int:
    """Clear the 'already shown' memory so everything is fresh again."""
    with connect() as conn:
        if kind:
            return _run(conn, "DELETE FROM user_seen WHERE user_id = ? AND kind = ?",
                        (user_id, kind))
        return _run(conn, "DELETE FROM user_seen WHERE user_id = ?", (user_id,))
