"""Storage: users, plans and run counts.

Two backends behind one API. Set DATABASE_URL to a Postgres connection string
(Neon, or any Postgres) and it is used; leave it unset and the app falls back to
a local SQLite file, which keeps `git clone && uvicorn` working with no service
to provision.

Queries are written once with '?' placeholders and rewritten for Postgres, and
both drivers hand back rows that behave like dicts, so callers do not care which
backend is live.
"""

from __future__ import annotations

import sqlite3
from contextlib import contextmanager
from datetime import datetime, timezone
from typing import Any, Iterator, Mapping, Optional

from config import DATABASE_URL, DB_PATH

Row = Mapping[str, Any]

IS_POSTGRES = bool(DATABASE_URL)

_pool = None

if IS_POSTGRES:  # pragma: no cover - exercised only with DATABASE_URL set
    from psycopg.rows import dict_row
    from psycopg_pool import ConnectionPool

    # Neon sits behind a pooler and can drop idle connections, so keep the pool
    # small, recycle connections, and check them out healthy.
    _pool = ConnectionPool(
        DATABASE_URL,
        min_size=0,
        max_size=5,
        max_idle=120,
        kwargs={"row_factory": dict_row, "autocommit": False},
        open=False,
    )


# --- schema -----------------------------------------------------------------
_SQLITE_SCHEMA = """
CREATE TABLE IF NOT EXISTS users (
    id                  INTEGER PRIMARY KEY AUTOINCREMENT,
    email               TEXT    NOT NULL UNIQUE,
    password_hash       TEXT    NOT NULL,
    plan                TEXT    NOT NULL DEFAULT 'free',
    stripe_customer_id  TEXT,
    plan_renews_at      TEXT,
    created_at          TEXT    NOT NULL
);

CREATE TABLE IF NOT EXISTS runs (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id     INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    created_at  TEXT    NOT NULL,
    companies   TEXT    NOT NULL DEFAULT '',
    found       INTEGER NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_runs_user_time ON runs(user_id, created_at);
CREATE INDEX IF NOT EXISTS idx_users_customer ON users(stripe_customer_id);
"""

_POSTGRES_SCHEMA = """
CREATE TABLE IF NOT EXISTS users (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email               TEXT   NOT NULL UNIQUE,
    password_hash       TEXT   NOT NULL,
    plan                TEXT   NOT NULL DEFAULT 'free',
    stripe_customer_id  TEXT,
    plan_renews_at      TEXT,
    created_at          TEXT   NOT NULL
);

CREATE TABLE IF NOT EXISTS runs (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    created_at  TEXT   NOT NULL,
    companies   TEXT   NOT NULL DEFAULT '',
    found       INTEGER NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_runs_user_time ON runs(user_id, created_at);
CREATE INDEX IF NOT EXISTS idx_users_customer ON users(stripe_customer_id);
"""


def _now() -> str:
    return datetime.now(timezone.utc).isoformat()


def month_start() -> str:
    now = datetime.now(timezone.utc)
    return now.replace(day=1, hour=0, minute=0, second=0, microsecond=0).isoformat()


def _q(sql: str) -> str:
    """'?' placeholders are written once; Postgres wants '%s'."""
    return sql.replace("?", "%s") if IS_POSTGRES else sql


def _ensure_pool_open() -> None:
    """Open the pool on first use.

    The pool is constructed with open=False so importing this module never
    reaches out to the network. Opening lazily here means any entry point works
    — the app's lifespan, a one-off script, a test — not just the paths that
    happen to call init_db() first. ConnectionPool.open() is a no-op once open.
    """
    assert _pool is not None
    _pool.open()


@contextmanager
def connect() -> Iterator[Any]:
    """A connection that commits on success and always closes/returns itself."""
    if IS_POSTGRES:
        _ensure_pool_open()
        assert _pool is not None
        with _pool.connection() as conn:   # commits on clean exit, rolls back on error
            yield conn
        return

    DB_PATH.parent.mkdir(parents=True, exist_ok=True)
    conn = sqlite3.connect(DB_PATH, timeout=10.0)
    conn.row_factory = sqlite3.Row
    conn.execute("PRAGMA foreign_keys = ON")
    try:
        yield conn
        conn.commit()
    finally:
        conn.close()


def _fetchone(conn: Any, sql: str, params: tuple) -> Optional[Row]:
    if IS_POSTGRES:
        with conn.cursor() as cur:
            cur.execute(_q(sql), params)
            return cur.fetchone()
    return conn.execute(sql, params).fetchone()


def _run(conn: Any, sql: str, params: tuple) -> int:
    """Execute a write; returns the number of rows affected."""
    if IS_POSTGRES:
        with conn.cursor() as cur:
            cur.execute(_q(sql), params)
            return cur.rowcount
    return conn.execute(sql, params).rowcount


def init_db() -> None:
    if IS_POSTGRES:
        with connect() as conn, conn.cursor() as cur:
            cur.execute(_POSTGRES_SCHEMA)
        return

    with connect() as conn:
        conn.executescript(_SQLITE_SCHEMA)


# --- users -------------------------------------------------------------------
def create_user(email: str, password_hash: str) -> int:
    sql = "INSERT INTO users (email, password_hash, created_at) VALUES (?, ?, ?)"
    with connect() as conn:
        if IS_POSTGRES:
            row = _fetchone(conn, sql + " RETURNING id", (email, password_hash, _now()))
            return int(row["id"])
        cur = conn.execute(sql, (email, password_hash, _now()))
        return int(cur.lastrowid)


def get_user_by_email(email: str) -> Optional[Row]:
    with connect() as conn:
        return _fetchone(conn, "SELECT * FROM users WHERE email = ?", (email,))


def get_user(user_id: int) -> Optional[Row]:
    with connect() as conn:
        return _fetchone(conn, "SELECT * FROM users WHERE id = ?", (user_id,))


def set_stripe_customer(user_id: int, customer_id: str) -> None:
    with connect() as conn:
        _run(conn, "UPDATE users SET stripe_customer_id = ? WHERE id = ?", (customer_id, user_id))


def set_plan(user_id: int, plan: str, renews_at: str | None = None) -> None:
    with connect() as conn:
        _run(conn, "UPDATE users SET plan = ?, plan_renews_at = ? WHERE id = ?",
             (plan, renews_at, user_id))


def set_plan_by_customer(customer_id: str, plan: str, renews_at: str | None = None) -> bool:
    with connect() as conn:
        return _run(conn,
                    "UPDATE users SET plan = ?, plan_renews_at = ? WHERE stripe_customer_id = ?",
                    (plan, renews_at, customer_id)) > 0


# --- runs / quota ------------------------------------------------------------
def record_run(user_id: int, companies: str, found: int) -> None:
    with connect() as conn:
        _run(conn, "INSERT INTO runs (user_id, created_at, companies, found) VALUES (?, ?, ?, ?)",
             (user_id, _now(), companies, found))


def runs_this_month(user_id: int) -> int:
    with connect() as conn:
        row = _fetchone(conn,
                        "SELECT COUNT(*) AS n FROM runs WHERE user_id = ? AND created_at >= ?",
                        (user_id, month_start()))
        return int(row["n"]) if row else 0


def close() -> None:
    """Release pooled connections. Without this the pool's worker threads are
    still alive at interpreter shutdown and psycopg_pool raises from __del__."""
    if IS_POSTGRES and _pool is not None:
        _pool.close()


def backend_name() -> str:
    return "postgres" if IS_POSTGRES else "sqlite"
