#!/bin/sh
# Generates frontend/_redirects at build time so the API origin comes from a
# Netlify environment variable instead of being committed into netlify.toml.
#
# Set API_ORIGIN in Netlify (Site settings > Environment variables) to the
# deployed FastAPI origin, e.g. https://leadclassifier-api.onrender.com
set -eu

OUT="frontend/_redirects"

if [ -z "${API_ORIGIN:-}" ]; then
  echo "WARNING: API_ORIGIN is not set — the site will build, but /api, /login"
  echo "         and /app will 404 until you set it and redeploy."
  : > "$OUT"
  exit 0
fi

# Strip any trailing slash so we never emit a double slash.
ORIGIN=$(printf '%s' "$API_ORIGIN" | sed 's:/*$::')

cat > "$OUT" <<EOF
# Generated by scripts/build-redirects.sh — do not edit by hand.
/api/*   ${ORIGIN}/api/:splat   200!
/login   ${ORIGIN}/login        200!
/app     ${ORIGIN}/app          200!
EOF

echo "Proxying API to ${ORIGIN}:"
sed 's/^/  /' "$OUT"
